[#68] Removes organization/title/subject areas/add cv from 'edit profile'
myhpom/MyHPOM pull request #102
Opened 2018-03-08 21:08 UTC by dsummersl

2018-03-09 18:45 UTC, philtuskha requested changes
Current changes look good / work well 👍 

Also, it is mentioned in bottom of issue to remove the iRods link.  Seems to be on line 100 of `profile.html`

2018-03-15 14:46 UTC, cbcunc approved these changes

2018-03-16 13:37 UTC, cbcunc approved these changes
Tested on VBox.

2018-03-16 14:05 UTC, cbcunc commented
I removed the iRODS account creation link.

2018-03-16 14:05 UTC, merged