[MH-71] Info about uploaded AD & delete view
myhpom/MyHPOM pull request #200
Opened 2018-07-18 15:02 UTC by nmashton

Per requirements, this fills out the "current AD" widget option and adds a delete endpoint (as well as a test for that endpoint).

To make this work, it was necessary to somewhat alter the logic in the preceding steps to ensure that an AD actually got uploaded in the correct manner. Hopefully the way in which this was done is clear overall.

2018-07-18 16:52 UTC, sharrisoncaktus commented on myhpom/templates/myhpom/upload/current_ad.html
> +        <a class="advance-directive-widget__button--primary" href="{{ request.user.advancedirective.document.url }}" target="_blank" rel="noopener noreferrer">Download</a>
This does not work when there is no document

2018-07-18 20:52 UTC, sharrisoncaktus reviewed
The main question I have is, how does this interact with the things that Dane has been working on? In particular, we decided not to do the upload itself in MH-77, but he was going to add it in MH-102. So you should probably review each other's pull requests now!

2018-07-19 17:14 UTC, dsummersl commented on myhpom/views/upload.py
> +@login_required
Should this be only ajax? If so add `@require_ajax`

2018-07-19 17:15 UTC, dsummersl commented on myhpom/views/upload.py
> +    form = UploadRequirementsForm()
This appears to be replaced by the `else` branch a few lines down.

2018-07-19 17:17 UTC, dsummersl commented on myhpom/views/upload.py
> +        return HttpResponseRedirect(reverse('myhpom:upload_current_ad'))
Add a test case for this to test_upload_view.py

2018-07-19 17:17 UTC, dsummersl requested changes
Looks great - couple small things noted.

2018-07-19 19:38 UTC, dsummersl approved these changes
👍

2018-07-19 19:41 UTC, merged