Mh 72  ad thumbnail
myhpom/MyHPOM pull request #228
Opened 2018-08-14 23:34 UTC by sharrisoncaktus

Now with this PR, when the user uploads an AD, a thumbnail is created and stored, and displayed in the dashboard sidebar. When the AD is deleted, the thumbnail is also deleted.

Installation: Requires ./hsctl rebuild the first time. This can now several minutes longer because it is downloading and compiling Ghostscript (gs) from C sources, which is a pretty heavy process. There unfortunately isn't a binary package available. 

Testing: 

* When an AD has been uploaded, confirm that the thumbnail has been created, is a .jpg "next to" the PDF in the storage, and is shown in the dashboard sidebar. Pretty exciting.
* When an AD has been deleted, confirm that the thumbnail has also been deleted from storage. "We don't need no" ... personal information security leaks.
* Test with filesystem (default, AD files stored in hydroshare/public/media/myhpom/advance_directives) and with iRODs (see https://github.com/myhpom/MyHPOM/pull/210).

2018-08-14 23:36 UTC, dsummersl commented
Can one of the admins verify this patch?

2018-08-15 15:18 UTC, nmashton requested changes
Per Slack discussion: love it, but let's add Pillow (as you suggested) so we can scale down the thumbnails without making them look bad. Do that and :shipit: .

2018-08-15 19:01 UTC, sharrisoncaktus commented
The latest commits add imagemagick post-processing to the thumbnail rendering, so that the thumbnail is always 508px wide (and thus a much smaller file than just a straight pdf to jpg at 150 dpi).

`./hsctl rebuild` is necessary, unfortunately, with this commit.

2018-08-15 19:12 UTC, nmashton approved these changes

2018-08-15 19:16 UTC, merged