[#80] Merge the hydroshare 1.14.1 branch.
myhpom/MyHPOM pull request #99
Opened 2018-03-07 20:36 UTC by dsummersl

I'd suggest the following method of testing this:

```bash
# stop and remove whatever docker setup you currently have:
docker-compose stop
docker-compose rm

# rebuild the docker images and the docker database from the repository:
./hsctl rebuild --db
```
Then go to http://localhost:8000 and try out all the common areas of the site.

2018-03-07 21:15 UTC, cbcunc commented
Alternatively, you can
`./hsctl stop`
and either of
`scripts\cleandocker`
or
`./hsctl reset_all`

2018-03-08 18:59 UTC, philtuskha requested changes
Besides those local setup changes, this all looks good to my bleary eyes and seems to work fine.

2018-03-08 18:59 UTC, philtuskha commented on config/hydroshare-config.yaml
>  HS_DATABASE: pg.myhpomdevelopment.sql
Looks like some of your personal settings for your purely Linux environment got encluded.

2018-03-08 19:03 UTC, dsummersl commented on config/hydroshare-config.yaml
>  HS_DATABASE: pg.myhpomdevelopment.sql
ooh, good catch, thanks...

2018-03-08 19:37 UTC, philtuskha approved these changes
👍

2018-03-16 14:18 UTC, cbcunc commented
Revert changes to hydroshare/local_settings.py

2018-03-26 17:29 UTC, merged